### ISSUE TITLE
2014以前のリンクです

### ISSUE THREAD

**Issue by kaisugi** [mqcmd196/utokyo_ist_math#1]
はじめまして。
ご存知でしたらすみませんが、過去5年よりも前のリンクが残っています。

2009: https://www.i.u-tokyo.ac.jp/edu/entra/pdf/archive/09math-j.pdf
2010: https://www.i.u-tokyo.ac.jp/edu/entra/pdf/archive/10math-j.pdf
2011: https://www.i.u-tokyo.ac.jp/edu/entra/pdf/archive/11math-j.pdf
2012: https://www.i.u-tokyo.ac.jp/edu/entra/pdf/archive/12math-j.pdf
2013: https://www.i.u-tokyo.ac.jp/edu/entra/pdf/archive/13math-j.pdf
2014: https://www.i.u-tokyo.ac.jp/edu/entra/pdf/archive/14math-j.pdf

（2008以前もありますが、今と違う6問構成です）

---

共通数学無くなるのが決まる前にここら辺をちょっと解いていたので、諸々片付いたら自分もPR出すかもしれないです。

**Comment by mqcmd196** [comment]
リンクありがとうございます！知りませんでした．
repositoryに追加しておきます．
